version: "3.3"
services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'lernsoftware'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  rabbit:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    expose:
      - '5672'
    restart: unless-stopped
  api:
    image: hub.noxz.dev/lernsoftware-backend:0.2.0

    environment:
      - DATABASE_URL=mysql+mysqlconnector://user:password@lernsoftware/lernsoftware?charset=utf8mb4
      - RABBIT_URL=amqp://guest:guest@rabbit:5672//

    volumes:
      - ./app:/app
      - ./data:/data
    links:
      - rabbit
    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: unless-stopped

  celery:
    image: hub.noxz.dev/lernsoftware-celery:0.2.0
    entrypoint: celery
    environment:
      - DATABASE_URL=mysql+mysqlconnector://user:password@lernsoftware/lernsoftware?charset=utf8mb4
      - RABBIT_URL=amqp://guest:guest@rabbit:5672//
    command: -A app.worker.tasks worker -c 2 --loglevel=DEBUG --without-gossip --without-mingle --without-heartbeat -Ofair
    volumes:
      - ./app:/app
      - ./data:/data
    links:
      - rabbit
    depends_on:
      - rabbit
      - db
    ports:
      - "5555:5555"
    restart: unless-stopped

  frontend:
    image: hub.noxz.dev/lernsoftware-frontend:0.2.0
    depends_on:
      - db
    ports:
      - "3000:80"
    restart: always
volumes:
  my-db:
