version: "3.3"
services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DATABASE_DB}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  rabbit:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    expose:
      - '5672'
  api:
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      - DATABASE_URL=mysql+mysqlconnector://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_IP}/${DATABASE_DB}?charset=utf8mb4
      - RABBIT_URL=amqp://${RABBIT_USER}:${RABBIT_PASSWORD}@${RABBIT_IP}:${RABBIT_PORT}//

    volumes:
      - ./app:/app
      - ./data:/data
    links:
      - rabbit
    depends_on:
      - rabbit
      - db
    ports:
      - "8000:8000"

  celery:
    build:
      context: .
      dockerfile: celery.dockerfile
    entrypoint: celery
    environment:
      - DATABASE_URL=mysql+mysqlconnector://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_IP}/${DATABASE_DB}?charset=utf8mb4
      - RABBIT_URL=amqp://${RABBIT_USER}:${RABBIT_PASSWORD}@${RABBIT_IP}:${RABBIT_PORT}//
    command: -A app.worker.tasks worker -c 2 --loglevel=DEBUG --without-gossip --without-mingle --without-heartbeat -Ofair
    volumes:
      - ./app:/app
      - ./data:/data
    links:
      - rabbit
    depends_on:
      - rabbit
      - db
    ports:
      - "5555:5555"

  frontend:
    image: lernsoftware-frontend:0.1.1.1
    depends_on:
      - db
    ports:
      - "3000:80"
    restart: always
volumes:
  my-db:
