version: '3'

services:
  db-dev:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    ports:
      - 3307:3306
    networks:
      - auth-network
    restart: unless-stopped
    volumes:
      - auth-db:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10

  supertokens-dev:
    image: registry.supertokens.io/supertokens/supertokens-mysql:latest
    container_name: supertokens
    depends_on:
      db-dev:
        condition: service_healthy
    ports:
      - 3567:3567
    environment:
      MYSQL_CONNECTION_URI: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DB}
    networks:
      - auth-network
    restart: unless-stopped
    healthcheck:
      test: >
        bash -c 'exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
      interval: 10s
      timeout: 5s
      retries: 5

  api-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    restart: unless-stopped
    depends_on:
      supertokens-dev:
        condition: service_healthy
    networks:
      - auth-network
    volumes:
      - ./app:/app
    environment:
      SENTRY_DSN: ${SENTRY_DSN}
      SENTRY_ENVIRONMENT: ${SENTRY_ENVIRONMENT}
      DASHBOARD_EMAIL: ${DASHBOARD_EMAIL}
      DASHBOARD_PASSWORD: ${DASHBOARD_PASSWORD}
    ports:
      - '3001:8000'

volumes:
  auth-db:

networks:
  auth-network:
    driver: bridge
