version: '3.3'
services:
  frontend:
    image: hafen.noxz.dev/patholearn-ai/frontend:${FRONTEND_VERSION}
    container_name: frontend-prod
    restart: unless-stopped
    networks:
      - patholearn-ai-network-prod
    ports:
      - "81:80"
  
  learn_api:
    image: hafen.noxz.dev/patholearn-ai/learn-api:${LEARN_API_VERSION}
    container_name: learn-api-prod
    restart: unless-stopped
    networks:
      - auth_auth-network-prod
      - patholearn-ai-network-prod
    environment:
      - DATABASE_URL=${DATABASE_DRIVER}://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_IP}/${DATABASE_DB}?${DATABASE_QUERY_PARAMETERS}
      - RABBIT_URL=amqp://${RABBIT_USER}:${RABBIT_PASSWORD}@${RABBIT_IP}:${RABBIT_PORT}//
      - SLIDE_URL=${SLIDE_INTERNAL_API_URL}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_URL=${MINIO_URL}
      - MINIO_SECURE=${MINIO_SECURE}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_HOST=${DATABASE_IP}
      - MYSQL_DATABASE=${DATABASE_DB}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - SENTRY_DSN=${SENTRY_LEARN_DSN}
      - SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT}
      - LEARN_API_ADMIN_EMAIL=${LEARN_API_ADMIN_EMAIL}
      - LEARN_API_ADMIN_PASSWORD=${LEARN_API_ADMIN_PASSWORD}
      - LEARN_API_ADMIN_FIRSTNAME=${LEARN_API_ADMIN_FIRSTNAME}
      - LEARN_API_ADMIN_LASTNAME=${LEARN_API_ADMIN_LASTNAME}
      - API_DOMAIN=${API_DOMAIN}
      - ANTI_CSRF=${ANTI_CSRF}
      - WEBSITE_DOMAIN=${WEBSITE_DOMAIN}
      - SUPERTOKENS_DOMAIN=${SUPERTOKENS_DOMAIN}
      - COOKIE_DOMAIN=${COOKIE_DOMAIN}
    ports:
      - '8011:8000'
    depends_on:
      learn_db:
        condition: service_healthy

  learn_db:
    image: mysql:latest
    container_name: learn-db-prod
    networks:
      - patholearn-ai-network-prod
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DATABASE_DB}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - '3316:${DATABASE_PORT}'
    volumes:
      - learn-db-data-prod:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10


  ai_api:
    image: hafen.noxz.dev/patholearn-ai/ai-api:${AI_API_VERSION}
    container_name: ai-api-prod
    restart: unless-stopped
    volumes:
      - ./clearml.conf:/root/clearml.conf
      - ai-api-data-prod:/data
    networks:
      - patholearn-ai-network-prod
      - ws_ws-network-prod
      - auth_auth-network-prod
    environment:
      - SENTRY_DSN=${SENTRY_AI_DSN}
      - SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT}
      - CLEARML_API=${CLEARML_API}
      - CLEARML_API_ACCESS_KEY=${CLEARML_API_ACCESS_KEY}
      - CLEARML_API_SECRET_KEY=${CLEARML_API_SECRET_KEY}
      - CELERY_BROKER_URL=amqp://${RABBIT_USER}:${RABBIT_PASSWORD}@${RABBIT_IP}:${RABBIT_PORT}//
      - WEBSOCKET_APP_ID=${WEBSOCKET_APP_ID}
      - WEBSOCKET_APP_KEY=${WEBSOCKET_APP_KEY}
      - WEBSOCKET_APP_SECRET=${WEBSOCKET_APP_SECRET}
      - WEBSOCKET_HOST=${WEBSOCKET_HOST}
      - WEBSOCKET_PORT=${WEBSOCKET_PORT}
      - WEBSOCKET_SSL=${WEBSOCKET_SSL}
      - DATABASE_URL=${MONGO_AI_DRIVER}://${MONGO_AI_USER}:${MONGO_AI_PASSWORD}@${MONGO_AI_IP}:${MONGO_AI_PORT} 
      - API_DOMAIN=${API_DOMAIN}
      - WEBSITE_DOMAIN=${WEBSITE_DOMAIN}
      - SUPERTOKENS_DOMAIN=${SUPERTOKENS_DOMAIN}
      - COOKIE_DOMAIN=${COOKIE_DOMAIN}
      - ANTI_CSRF=${ANTI_CSRF}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_SECURE=${MINIO_SECURE}
      - MINIO_URL=${MINIO_URL}
      - AI_STORAGE_INTERNAL_URL=${AI_STORAGE_INTERNAL_URL}
      - AI_STORAGE_PUBLIC_URL=${AI_STORAGE_PUBLIC_URL}
      - LEARN_API_HOST=${LEARN_API_HOST}
      - LEARN_API_PORT=${LEARN_API_PORT}
      - SLIDE_API_HOST=${SLIDE_API_HOST}
      - SLIDE_API_PORT=${SLIDE_API_PORT}
    ports:
      - '48888:8000'

  ai_api_worker:
    image: hafen.noxz.dev/patholearn-ai/ai-api-worker:${AI_API_VERSION}
    restart: unless-stopped
    container_name: ai-api-worker
    networks:
      - patholearn-ai-network-prod
      - ws_ws-network-prod
      - auth_auth-network-prod
    volumes:
      - ./clearml.conf:/root/clearml.conf
      - ai-api-data-prod:/data
    environment:
      - SENTRY_DSN=${SENTRY_AI_DSN}
      - SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT}
      - CLEARML_API=${CLEARML_API}
      - CLEARML_API_ACCESS_KEY=${CLEARML_API_ACCESS_KEY}
      - CLEARML_API_SECRET_KEY=${CLEARML_API_SECRET_KEY}
      - CELERY_BROKER_URL=amqp://${RABBIT_USER}:${RABBIT_PASSWORD}@${RABBIT_IP}:${RABBIT_PORT}//
      - WEBSOCKET_APP_ID=${WEBSOCKET_APP_ID}
      - WEBSOCKET_APP_KEY=${WEBSOCKET_APP_KEY}
      - WEBSOCKET_APP_SECRET=${WEBSOCKET_APP_SECRET}
      - WEBSOCKET_HOST=${WEBSOCKET_HOST}
      - WEBSOCKET_PORT=${WEBSOCKET_PORT}
      - WEBSOCKET_SSL=${WEBSOCKET_SSL}
      - DATABASE_URL=${MONGO_AI_DRIVER}://${MONGO_AI_USER}:${MONGO_AI_PASSWORD}@${MONGO_AI_IP}:${MONGO_AI_PORT}
      - ANTI_CSRF=${ANTI_CSRF}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_SECURE=${MINIO_SECURE}
      - MINIO_URL=${MINIO_URL}
      - LEARN_API_HOST=${LEARN_API_HOST}
      - LEARN_API_PORT=${LEARN_API_PORT}
      - SLIDE_API_HOST=${SLIDE_API_HOST}
      - SLIDE_API_PORT=${SLIDE_API_PORT}
    command: celery --app worker.worker.celery_app worker --loglevel=info --without-gossip --without-mingle --without-heartbeat -Ofair -Q ai_api

  ai_worker:
    image: hafen.noxz.dev/patholearn-ai/ai-worker:${AI_API_VERSION}
    container_name: ai-worker-prod
    restart: unless-stopped
    volumes:
      - ./clearml.conf:/root/clearml.conf
      - ./schedule.db:/app/scheduler/schedule.db
    networks:
      - patholearn-ai-network-prod
      - ws_ws-network-prod
    command: celery --app worker.celery_app worker --loglevel=info --without-gossip --without-mingle --without-heartbeat -Ofair -Q ai
    environment:
      - CELERY_BROKER_URL=amqp://${RABBIT_USER}:${RABBIT_PASSWORD}@${RABBIT_IP}:${RABBIT_PORT}//
      - DATABASE_URL=${MONGO_AI_DRIVER}://${MONGO_AI_USER}:${MONGO_AI_PASSWORD}@${MONGO_AI_IP}:${MONGO_AI_PORT}
      - WEBSOCKET_APP_ID=${WEBSOCKET_APP_ID}
      - WEBSOCKET_APP_KEY=${WEBSOCKET_APP_KEY}
      - WEBSOCKET_APP_SECRET=${WEBSOCKET_APP_SECRET}
      - WEBSOCKET_HOST=${WEBSOCKET_HOST}
      - WEBSOCKET_PORT=${WEBSOCKET_PORT}
      - WEBSOCKET_SSL=${WEBSOCKET_SSL}

  ai_worker_beat:
    image: hafen.noxz.dev/patholearn-ai/ai-worker:${AI_API_VERSION}
    container_name: ai-worker-beat-prod
    restart: unless-stopped
    volumes:
      - ./clearml.conf:/root/clearml.conf
      - ./schedule.db:/app/scheduler/schedule.db
    networks:
      - patholearn-ai-network-prod
      - ws_ws-network-prod
    command: celery --app worker.celery_app beat -S app.scheduler.schedulers:DatabaseScheduler --loglevel=info
    environment:
      - CELERY_BROKER_URL=amqp://${RABBIT_USER}:${RABBIT_PASSWORD}@${RABBIT_IP}:${RABBIT_PORT}//
      - DATABASE_URL=${MONGO_AI_DRIVER}://${MONGO_AI_USER}:${MONGO_AI_PASSWORD}@${MONGO_AI_IP}:${MONGO_AI_PORT}
      - WEBSOCKET_APP_ID=${WEBSOCKET_APP_ID}
      - WEBSOCKET_APP_KEY=${WEBSOCKET_APP_KEY}
      - WEBSOCKET_APP_SECRET=${WEBSOCKET_APP_SECRET}
      - WEBSOCKET_HOST=${WEBSOCKET_HOST}
      - WEBSOCKET_PORT=${WEBSOCKET_PORT}
      - WEBSOCKET_SSL=${WEBSOCKET_SSL}

  ai_db:
    image: mongo:latest
    container_name: ai-db-prod
    restart: unless-stopped
    networks:
      - patholearn-ai-network-prod
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_AI_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_AI_INITDB_ROOT_PASSWORD}
    ports:
      - '47018:${MONGO_AI_PORT}'
    volumes:
      - ai-db-data-prod:/mongodb

  slide_api:
    image: hafen.noxz.dev/patholearn-ai/slide-api:${SLIDE_API_VERSION}
    container_name: slide-api-prod
    restart: unless-stopped
    networks:
      - patholearn-ai-network-prod
    volumes:
      - slide-data-prod:/data
    ports:
      - '48001:8000'
    command: uvicorn app.app:app --host 0.0.0.0 --port 8000 --no-server-header
    environment:
      - CELERY_BROKER_URL=amqp://${RABBIT_USER}:${RABBIT_PASSWORD}@${RABBIT_IP}:${RABBIT_PORT}//
      - DATABASE_URL=${MONGO_DRIVER}://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_IP}:${MONGO_PORT}
      - MONGO_DB=${MONGO_DB}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_URL=${MINIO_URL}
      - SENTRY_DSN=${SENTRY_SLIDE_DSN}
      - SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT}
    depends_on:
      - slide_db

  slide_worker:
    image: hafen.noxz.dev/patholearn-ai/slide-api:${SLIDE_API_VERSION}
    container_name: slide-worker-prod
    restart: unless-stopped
    networks:
      - patholearn-ai-network-prod
    depends_on:
      - slide_api
    command: celery --app worker.celery_app worker --loglevel=info
    volumes:
      - slide-data-prod:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_URL=${MINIO_URL}
      - MONGO_DB=${MONGO_DB}
      - CELERY_BROKER_URL=amqp://${RABBIT_USER}:${RABBIT_PASSWORD}@${RABBIT_IP}:${RABBIT_PORT}//
      - DATABASE_URL=${MONGO_DRIVER}://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_IP}:${MONGO_PORT}

  slide_db:
    image: mongo:latest
    container_name: slide-db-prod
    restart: unless-stopped
    networks:
      - patholearn-ai-network-prod
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - slide-db-data-prod:/data
    ports:
      - '47017:${MONGO_PORT}'


#   minio:
#     image: minio/minio
#     restart: unless-stopped
#     networks:
#       - patholearn-network
#     ports:
#       - '9000:9000'
#       - '9001:9001'
#     volumes:
#       - ./minio_data:/data
#     environment:
#       - MINIO_ROOT_USER=${MINIO_ROOT_USER}
#       - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
#     command: server --console-address ":9001" /data

  rabbit:
    image: rabbitmq:latest
    container_name: rabbit-prod
    restart: unless-stopped
    networks:
      - patholearn-ai-network-prod
    ports:
      - '45672:5672'

networks:
  auth_auth-network-prod:
    external: true
  ws_ws-network-prod:
    external: true
  patholearn-ai-network-prod:
    external: false

volumes:
  learn-db-data-prod:
  slide-db-data-prod:
  slide-data-prod:
  ai-db-data-prod:
  ai-api-data-prod:
