version: '3.3'

services:
  ws:
    image: quay.io/soketi/soketi:1.4-16-debian
    restart: unless-stopped
    environment:
      - SOKETI_DEBUG=${DEBUG:-1}
      - SOKETI_DEFAULT_APP_ID=${PUSHER_APP_ID:-some-id}
      - SOKETI_DEFAULT_APP_KEY=${PUSHER_APP_KEY:-app-key}
      - SOKETI_DEFAULT_APP_SECRET=${PUSHER_APP_SECRET:-some-app-secret}
      - SOKETI_METRICS_ENABLED=${SOKETI_METRICS_ENABLED:-false}
      - METRICS_SERVER_PORT=${METRICS_SERVER_PORT:-9601}
      - DEFAULT_APP_ENABLE_CLIENT_MESSAGES=${DEFAULT_APP_ENABLE_CLIENT_MESSAGES:-false}

    ports:
      - "${SOKETI_PORT:-6001}:6001"
      - "${SOKETI_METRICS_SERVER_PORT:-9601}:9601"
    networks:
      - ws-network

networks:
  ws-network:
    driver: bridge