name: lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  learn_api:
    runs-on: ubuntu-latest
    working-directory: ./backend
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
  slide_api:
    runs-on: ubuntu-latest
    working-directory: ./pyramid-creator
    steps:
      - uses: actions/checkout@v2
      - uses: pdf/black@stable